version: '3.4'

services:
  frontend:
    build:
      context: .
      dockerfile: ./WebsiteFrontMagazinE/WebsiteFrontMagazinE.Server/Dockerfile
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - magazineapi
    networks:
      - mssql_network
 
  magazineapi:
    build:
      context: .
      dockerfile: ./MagazinEAPI/Dockerfile
      args:
        - configuration=Release
    ports:
      - 8082:8082
      - 8083:8083
    depends_on:
      - mssql
    networks:
      - mssql_network
       


  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_express
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express   # Specifies the edition to run as Express
      - MSSQL_SA_PASSWORD=Pass123Pass123Pass123   # Set the SA (System Administrator) password
    ports:
      - "1434:1433"  # Expose SQL Server port 1433
    volumes:
      - mssql_data:/var/opt/mssql  # Persist database data outside of the container
      - ./backend/scripts:/scripts  # Mount for SQL scripts
    networks:
      - mssql_network
   
volumes:
  mssql_data: # Named volume to persist data
 
networks:
  mssql_network:
    driver: bridge
