// <auto-generated />
using System;
using MagazinEAPI.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MagazinEAPI.Migrations
{
    [DbContext(typeof(RolesBasedContext))]
    [Migration("20250607182837_NameReaderSeed")]
    partial class NameReaderSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeOfPublication")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isPremium")
                        .HasColumnType("bit");

                    b.Property<bool>("isPublished")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Content = "Tech giants are investing in AI, quantum computing, and biotech.",
                            Introduction = "Technology is evolving faster than ever.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Future of Technology",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Content = "NASA and SpaceX plan new missions to explore Mars by 2030.",
                            Introduction = "Mars might be our next home.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Exploring Space: Mars Mission",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Content = "Rising sea levels and extreme weather are the new normal.",
                            Introduction = "Climate change is reshaping our world.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Climate Change and Its Impact",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Content = "EVs are cleaner and smarter, with self-driving features.",
                            Introduction = "Electric cars are changing the auto industry.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Rise of Electric Vehicles",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Content = "AI is helping doctors detect diseases earlier than ever.",
                            Introduction = "AI is transforming how we diagnose illness.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "AI in Healthcare",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Content = "Supply chains and voting systems are being rebuilt with blockchain.",
                            Introduction = "Blockchain isn’t just for crypto.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Blockchain Beyond Bitcoin",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Content = "Studies link screen time with anxiety and depression.",
                            Introduction = "Social media affects our mental state.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Psychology of Social Media",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Content = "From Picasso to Pollock, modern art broke all rules.",
                            Introduction = "Art has changed radically in the 20th century.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "History of Modern Art",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Content = "Cybersecurity now relies on AI to detect anomalies.",
                            Introduction = "Cyber threats are getting more complex.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cybersecurity Trends 2025",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            Content = "Smartphones have become digital Swiss Army knives.",
                            Introduction = "Phones have come a long way.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Evolution of Smartphones",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 11,
                            AuthorId = 1,
                            Content = "Flexible hours and values drive Gen Z’s work choices.",
                            Introduction = "Gen Z is redefining work culture.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gen Z in the Workforce",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 12,
                            AuthorId = 1,
                            Content = "Wind, solar, and storage are reshaping power grids.",
                            Introduction = "Green tech is our future.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Renewable Energy Innovations",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 13,
                            AuthorId = 1,
                            Content = "Sleep regulates memory, mood, and immune function.",
                            Introduction = "Sleep is more important than we think.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Science Behind Sleep",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 14,
                            AuthorId = 1,
                            Content = "Data analysis improves performance and reduces injuries.",
                            Introduction = "Sports now run on data.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sports Analytics: A New Era",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 15,
                            AuthorId = 1,
                            Content = "Quantum tech could revolutionize encryption and materials science.",
                            Introduction = "Quantum computers could solve the unsolvable.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Understanding Quantum Computing",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 16,
                            AuthorId = 1,
                            Content = "Smart infrastructure optimizes traffic, energy, and safety.",
                            Introduction = "Cities are getting smarter.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Smart Cities: Living Tomorrow",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 17,
                            AuthorId = 1,
                            Content = "Schools and workplaces must support mental wellness.",
                            Introduction = "Mental health should be a priority.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mental Health Awareness",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 18,
                            AuthorId = 1,
                            Content = "Remote tools like Zoom and Slack dominate business.",
                            Introduction = "Working from home is here to stay.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Growth of Remote Work",
                            isPremium = false,
                            isPublished = true
                        },
                        new
                        {
                            Id = 19,
                            AuthorId = 1,
                            Content = "Plastic pollution and warming threaten marine life.",
                            Introduction = "Our oceans need help.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ocean Conservation Efforts",
                            isPremium = true,
                            isPublished = true
                        },
                        new
                        {
                            Id = 20,
                            AuthorId = 1,
                            Content = "Games are cultural icons with massive economic impact.",
                            Introduction = "Gaming is now bigger than Hollywood.",
                            ReviewerId = 1,
                            TimeOfPublication = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gaming Industry: What's Next?",
                            isPremium = false,
                            isPublished = true
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedById")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ParentId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            AuthorId = 1,
                            Content = "This is comment #1 on article #1. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            AuthorId = 1,
                            Content = "This is comment #2 on article #2. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            AuthorId = 1,
                            Content = "This is comment #3 on article #3. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4,
                            ArticleId = 4,
                            AuthorId = 1,
                            Content = "This is comment #4 on article #4. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5,
                            ArticleId = 5,
                            AuthorId = 1,
                            Content = "This is comment #5 on article #5. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6,
                            ArticleId = 6,
                            AuthorId = 1,
                            Content = "This is comment #6 on article #6. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 7,
                            ArticleId = 7,
                            AuthorId = 1,
                            Content = "This is comment #7 on article #7. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 8,
                            ArticleId = 8,
                            AuthorId = 1,
                            Content = "This is comment #8 on article #8. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 9,
                            ArticleId = 9,
                            AuthorId = 1,
                            Content = "This is comment #9 on article #9. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 10,
                            ArticleId = 10,
                            AuthorId = 1,
                            Content = "This is comment #10 on article #10. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 11,
                            ArticleId = 11,
                            AuthorId = 1,
                            Content = "This is comment #11 on article #11. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 12,
                            ArticleId = 12,
                            AuthorId = 1,
                            Content = "This is comment #12 on article #12. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 13,
                            ArticleId = 13,
                            AuthorId = 1,
                            Content = "This is comment #13 on article #13. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 14,
                            ArticleId = 14,
                            AuthorId = 1,
                            Content = "This is comment #14 on article #14. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 15,
                            ArticleId = 15,
                            AuthorId = 1,
                            Content = "This is comment #15 on article #15. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 16,
                            ArticleId = 16,
                            AuthorId = 1,
                            Content = "This is comment #16 on article #16. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 17,
                            ArticleId = 17,
                            AuthorId = 1,
                            Content = "This is comment #17 on article #17. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 18,
                            ArticleId = 18,
                            AuthorId = 1,
                            Content = "This is comment #18 on article #18. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 19,
                            ArticleId = 19,
                            AuthorId = 1,
                            Content = "This is comment #19 on article #19. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 20,
                            ArticleId = 20,
                            AuthorId = 1,
                            Content = "This is comment #20 on article #20. What a great article!!!",
                            Date = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.CommentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ManagedById")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportAuthorId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("ManagedById");

                    b.HasIndex("ReportAuthorId");

                    b.ToTable("CommentReports");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.Dislike", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Dislikes");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.Like", b =>
                {
                    b.Property<int>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Likes");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.PhotoArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("PhotoId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "PhotoId");

                    b.HasIndex("PhotoId");

                    b.ToTable("PhotoArticles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Super tag 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Super tag 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Super tag 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Super tag 4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Super tag 5"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Super tag 6"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Super tag 7"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Super tag 8"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Super tag 9"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Super tag 10"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Super tag 11"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Super tag 12"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Super tag 13"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Super tag 14"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Super tag 15"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Super tag 16"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Super tag 17"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Super tag 18"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Super tag 19"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Super tag 20"
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.TagArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TagArticles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Requests.PublishRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PublishState")
                        .HasColumnType("int");

                    b.Property<int?>("ReviewerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ReviewerId");

                    b.ToTable("PublishRequests");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Requests.RegisterRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSuccesfull")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("RegisterRequests");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Requests.UnbanRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BanId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SolvedById")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BanId");

                    b.HasIndex("SolvedById");

                    b.ToTable("UnbanRequests");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Admins.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "2c5w174e-3b0e-446f-86af-483d56fd7214"
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7210",
                            Description = "Admin",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7211",
                            Description = "Reader",
                            Name = "Reader",
                            NormalizedName = "READER"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7212",
                            Description = "Editor",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7213",
                            Description = "HeadEditor",
                            Name = "HeadEditor",
                            NormalizedName = "HEADEDITOR"
                        },
                        new
                        {
                            Id = "2c5e174e-3b0e-446f-86af-483d56fd7214",
                            Description = "Journalist",
                            Name = "Journalist",
                            NormalizedName = "JOURNALIST"
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "2c5w174e-3b0e-446f-86af-483d56fd7214",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "599c3aa8-eda2-4861-a51d-5c6ba68596c0",
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEGjtaYT1QQugEtDzxCHL5AD80LCJ9rX+EAYl44HijtqzIHZXfphoRhNjjBW2WujvIw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c5ba1859-83da-4fed-b0b8-965f2b80d3ea",
                            State = 0,
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        },
                        new
                        {
                            Id = "2c5w174e-3b0e-486f-86af-483d56fd7213",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd2d325e-0c77-4a07-9b08-42ed37020384",
                            Email = "headeditor@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "HEADEDITOR@EXAMPLE.COM",
                            NormalizedUserName = "HEADEDITOR",
                            PasswordHash = "AQAAAAIAAYagAAAAENKzyCo5g+I320Z15/ZxFZopnss/ggALZ73kN4z2QWrVG+NRZz9bk7L+w7dSBYa4Ag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd7090c7-30a5-46d5-9e05-815f38bbd6ab",
                            State = 0,
                            TwoFactorEnabled = false,
                            UserName = "HeadEditor"
                        },
                        new
                        {
                            Id = "2c5w179e-3b0e-446f-86af-483d56fd7212",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd2d323e-0c77-4a07-9b08-42ed37020384",
                            Email = "editor@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDITOR@EXAMPLE.COM",
                            NormalizedUserName = "EDITOR",
                            PasswordHash = "AQAAAAIAAYagAAAAEDaQJNcmsFaqlvYpylJ8LL9S9aYOCTsB7PtdbsCQsymITYP5lz9PK77Q3FJw+xFmGw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd709037-30a5-46d5-9e05-815f38bbd6ab",
                            State = 0,
                            TwoFactorEnabled = false,
                            UserName = "Editor"
                        },
                        new
                        {
                            Id = "2c5w174r-3b0e-446f-86af-483d56fd7214",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd2d323e-0c77-4a07-9b08-42ed38020384",
                            Email = "journalist@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "JOURNALIST@EXAMPLE.COM",
                            NormalizedUserName = "JOURNALIST",
                            PasswordHash = "AQAAAAIAAYagAAAAEOAXkcsy7IiVg45vv09dUPqtwHOzbwnO1kOLG7lC4iVA9G8VOr2qjWxBcGtQN1zC+w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd709037-30a5-46d5-9e05-815f38b6d6ab",
                            State = 0,
                            TwoFactorEnabled = false,
                            UserName = "Journalist"
                        },
                        new
                        {
                            Id = "2c5w174r-3b0e-446f-86af-483d56fd7211",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dd2d323e-0c77-4a07-9b08-422d38020384",
                            Email = "reader@example.com",
                            EmailConfirmed = true,
                            FirstName = "Grzegorz",
                            LastName = "Brzęczyszczykiewicz",
                            LockoutEnabled = false,
                            NormalizedEmail = "READER@EXAMPLE.COM",
                            NormalizedUserName = "READER",
                            PasswordHash = "AQAAAAIAAYagAAAAECAtlY2RA/vjLYvmweL9IBRZJl25Few+FUY8QMsC3/rJADAsQxzWxlD4QR4/ZJoSAw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "dd709037-30a5-46d5-9e05-515f38b6d6ab",
                            State = 0,
                            TwoFactorEnabled = false,
                            UserName = "reader"
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Ban", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("BanEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BanStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("Bans");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.Editor", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HeadEditorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Editors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "2c5w179e-3b0e-446f-86af-483d56fd7212",
                            HeadEditorId = 1
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.HeadEditor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("HeadEditors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "2c5w174e-3b0e-486f-86af-483d56fd7213"
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.TagEditor", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("EditorId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "EditorId");

                    b.HasIndex("EditorId");

                    b.ToTable("TagEditors");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Journalists.Journalist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("HeadEditorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("HeadEditorId");

                    b.ToTable("Journalists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "2c5w174r-3b0e-446f-86af-483d56fd7214",
                            HeadEditorId = 1
                        });
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.FavoriteArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteArticles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.OwnedArticles", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("OwnedArticles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.TagUser", b =>
                {
                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TagId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TagUsers");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.ToReadArticle", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ToReadArticles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("Readers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationUserId = "2c5w174r-3b0e-446f-86af-483d56fd7211"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "2c5w174e-3b0e-446f-86af-483d56fd7214",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7210"
                        },
                        new
                        {
                            UserId = "2c5w174e-3b0e-486f-86af-483d56fd7213",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7213"
                        },
                        new
                        {
                            UserId = "2c5w179e-3b0e-446f-86af-483d56fd7212",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7212"
                        },
                        new
                        {
                            UserId = "2c5w174r-3b0e-446f-86af-483d56fd7214",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7214"
                        },
                        new
                        {
                            UserId = "2c5w174r-3b0e-446f-86af-483d56fd7211",
                            RoleId = "2c5e174e-3b0e-446f-86af-483d56fd7211"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Article", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.Journalists.Journalist", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId");

                    b.HasOne("MagazinEAPI.Models.Users.Editors.Editor", "Reviewer")
                        .WithMany("Articles")
                        .HasForeignKey("ReviewerId");

                    b.Navigation("Author");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.Comment", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Article", "Article")
                        .WithMany("Comments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Admins.Admin", "DeletedBy")
                        .WithMany("DeletedComments")
                        .HasForeignKey("DeletedById");

                    b.HasOne("MagazinEAPI.Models.Articles.Comment.Comment", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Article");

                    b.Navigation("Author");

                    b.Navigation("DeletedBy");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.CommentReport", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Comment.Comment", "Comment")
                        .WithMany("Reports")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Admins.Admin", "ManagedBy")
                        .WithMany("ManagedCommentReports")
                        .HasForeignKey("ManagedById");

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "ReportAuthor")
                        .WithMany("ReportedComments")
                        .HasForeignKey("ReportAuthorId");

                    b.Navigation("Comment");

                    b.Navigation("ManagedBy");

                    b.Navigation("ReportAuthor");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.Dislike", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Comment.Comment", "Comment")
                        .WithMany("Dislikes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("Dislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.Like", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Comment.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.PhotoArticle", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Article", "Article")
                        .WithMany("PhotoArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Articles.Photo", "Photo")
                        .WithMany("PhotoArticles")
                        .HasForeignKey("PhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.TagArticle", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Article", "Article")
                        .WithMany("TagArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Articles.Tag", "Tag")
                        .WithMany("TagArticles")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Requests.PublishRequest", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Article", "Article")
                        .WithMany("PublishRequests")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Editors.Editor", "Reviewer")
                        .WithMany("PublishRequests")
                        .HasForeignKey("ReviewerId");

                    b.Navigation("Article");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Requests.UnbanRequest", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.Ban", "Ban")
                        .WithMany("UnbanRequests")
                        .HasForeignKey("BanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Admins.Admin", "SolvedBy")
                        .WithMany("SolvedUnbanRequests")
                        .HasForeignKey("SolvedById");

                    b.Navigation("Ban");

                    b.Navigation("SolvedBy");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Admins.Admin", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("Admin")
                        .HasForeignKey("MagazinEAPI.Models.Users.Admins.Admin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Ban", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.Admins.Admin", "Admin")
                        .WithMany("Bans")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("Bans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.Editor", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("Editor")
                        .HasForeignKey("MagazinEAPI.Models.Users.Editors.Editor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Editors.HeadEditor", "HeadEditor")
                        .WithMany("EditorsUnder")
                        .HasForeignKey("Id");

                    b.Navigation("ApplicationUser");

                    b.Navigation("HeadEditor");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.HeadEditor", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("HeadEditor")
                        .HasForeignKey("MagazinEAPI.Models.Users.Editors.HeadEditor", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.TagEditor", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.Editors.Editor", "Editor")
                        .WithMany("AllowedTagEditors")
                        .HasForeignKey("EditorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Articles.Tag", "Tag")
                        .WithMany("TagEditors")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Editor");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Journalists.Journalist", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("Journalist")
                        .HasForeignKey("MagazinEAPI.Models.Users.Journalists.Journalist", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Editors.HeadEditor", "HeadEditor")
                        .WithMany("JournalistsUnder")
                        .HasForeignKey("HeadEditorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("HeadEditor");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.FavoriteArticle", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Article", "Article")
                        .WithMany("FavoriteArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("FavoriteArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.OwnedArticles", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Article", "Article")
                        .WithMany("OwnedToArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("OwnedToArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.Subscription", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.TagUser", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Tag", "Tag")
                        .WithMany("TagUsers")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("FavouriteTagUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.ToReadArticle", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Articles.Article", "Article")
                        .WithMany("ToReadArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.Readers.User", "User")
                        .WithMany("ToReadArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.User", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", "ApplicationUser")
                        .WithOne("User")
                        .HasForeignKey("MagazinEAPI.Models.Users.Readers.User", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MagazinEAPI.Models.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Article", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavoriteArticles");

                    b.Navigation("OwnedToArticles");

                    b.Navigation("PhotoArticles");

                    b.Navigation("PublishRequests");

                    b.Navigation("TagArticles");

                    b.Navigation("ToReadArticles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Comment.Comment", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Dislikes");

                    b.Navigation("Likes");

                    b.Navigation("Reports");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Photo", b =>
                {
                    b.Navigation("PhotoArticles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Articles.Tag", b =>
                {
                    b.Navigation("TagArticles");

                    b.Navigation("TagEditors");

                    b.Navigation("TagUsers");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Admins.Admin", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("DeletedComments");

                    b.Navigation("ManagedCommentReports");

                    b.Navigation("SolvedUnbanRequests");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.ApplicationUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Editor");

                    b.Navigation("HeadEditor");

                    b.Navigation("Journalist");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Ban", b =>
                {
                    b.Navigation("UnbanRequests");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.Editor", b =>
                {
                    b.Navigation("AllowedTagEditors");

                    b.Navigation("Articles");

                    b.Navigation("PublishRequests");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Editors.HeadEditor", b =>
                {
                    b.Navigation("EditorsUnder");

                    b.Navigation("JournalistsUnder");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Journalists.Journalist", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("MagazinEAPI.Models.Users.Readers.User", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Comments");

                    b.Navigation("Dislikes");

                    b.Navigation("FavoriteArticles");

                    b.Navigation("FavouriteTagUsers");

                    b.Navigation("Likes");

                    b.Navigation("OwnedToArticles");

                    b.Navigation("ReportedComments");

                    b.Navigation("Subscriptions");

                    b.Navigation("ToReadArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
